export const data = [
  {
    index: 1,
    carrier: 'Secured',
    deadhead: 'Cadillac',
    safety: 'Realpoint',
    price: 348,
    edit: true,
    available: 38178,
  },
  {
    index: 2,
    carrier: 'client-driven',
    deadhead: 'Hummer',
    safety: 'Quaxo',
    price: 590,
    edit: false,
    available: 88573,
  },
  {
    index: 3,
    carrier: 'Networked',
    deadhead: 'Volkswagen',
    safety: 'Plajo',
    price: 962,
    edit: false,
    available: 83543,
  },
  {
    index: 4,
    carrier: 'Balanced',
    deadhead: 'Lexus',
    safety: 'Topiczoom',
    price: 322,
    edit: true,
    available: 33686,
  },
  {
    index: 5,
    carrier: 'full-range',
    deadhead: 'Hyundai',
    safety: 'Photobug',
    price: 873,
    edit: false,
    available: 34780,
  },
  {
    index: 6,
    carrier: 'middleware',
    deadhead: 'Infiniti',
    safety: 'Linklinks',
    price: 810,
    edit: true,
    available: 64301,
  },
  {
    index: 7,
    carrier: 'methodology',
    deadhead: 'Dodge',
    safety: 'Dynava',
    price: 301,
    edit: true,
    available: 95246,
  },
  {
    index: 8,
    carrier: 'Realigned',
    deadhead: 'Audi',
    safety: 'Bubbletube',
    price: 925,
    edit: true,
    available: 84582,
  },
  {
    index: 9,
    carrier: 'core',
    deadhead: 'Ford',
    safety: 'Riffpath',
    price: 39,
    edit: true,
    available: 83510,
  },
  {
    index: 10,
    carrier: 'artificial intelligence',
    deadhead: 'Jeep',
    safety: 'Twitterbridge',
    price: 639,
    edit: true,
    available: 66908,
  },
  {
    index: 11,
    carrier: 'hub',
    deadhead: 'Volvo',
    safety: 'Plajo',
    price: 609,
    edit: true,
    available: 10067,
  },
  {
    index: 12,
    carrier: 'mobile',
    deadhead: 'Ford',
    safety: 'Quaxo',
    price: 800,
    edit: true,
    available: 73423,
  },
  {
    index: 13,
    carrier: 'initiative',
    deadhead: 'Mitsubishi',
    safety: 'Tekfly',
    price: 717,
    edit: true,
    available: 19562,
  },
  {
    index: 14,
    carrier: 'data-warehouse',
    deadhead: 'Volvo',
    safety: 'Meembee',
    price: 403,
    edit: false,
    available: 72313,
  },
  {
    index: 15,
    carrier: 'success',
    deadhead: 'Buick',
    safety: 'Tagcat',
    price: 228,
    edit: false,
    available: 62083,
  },
  {
    index: 16,
    carrier: 'Optional',
    deadhead: 'Toyota',
    safety: 'Edgeify',
    price: 807,
    edit: true,
    available: 56416,
  },
  {
    index: 17,
    carrier: 'even-keeled',
    deadhead: 'Volkswagen',
    safety: 'Agimba',
    price: 659,
    edit: false,
    available: 94667,
  },
  {
    index: 18,
    carrier: 'function',
    deadhead: 'Audi',
    safety: 'Yadel',
    price: 43,
    edit: true,
    available: 13609,
  },
  {
    index: 19,
    carrier: '5th generation',
    deadhead: 'GMC',
    safety: 'Mycat',
    price: 913,
    edit: false,
    available: 89596,
  },
  {
    index: 20,
    carrier: 'intangible',
    deadhead: 'Lexus',
    safety: 'Topicware',
    price: 435,
    edit: true,
    available: 67060,
  },
];
